apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-vectoradd
  namespace: agents
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gpu-vectoradd
          image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0
          env:
            - name: LD_LIBRARY_PATH
              value: /run/opengl-driver/lib:/usr/local/cuda/compat:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: opengl-driver
              mountPath: /run/opengl-driver
              readOnly: true
            - name: nix-store
              mountPath: /nix/store
              readOnly: true
      volumes:
        - name: opengl-driver
          hostPath:
            path: /run/opengl-driver
            type: Directory
        - name: nix-store
          hostPath:
            path: /nix/store
            type: Directory
