apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nvidia-device-plugin-ctr
          image: nvcr.io/nvidia/k8s-device-plugin:v0.19.1
          args:
            - --nvidia-driver-root=/driver-root
            - --nvidia-dev-root=/
            - --pass-device-specs=true
          env:
            - name: LD_LIBRARY_PATH
              value: /driver-root/lib
          securityContext:
            privileged: true
          volumeMounts:
            - name: kubelet-device-plugins-dir
              mountPath: /var/lib/kubelet/device-plugins
            - name: nvidia-driver-root
              mountPath: /driver-root
              readOnly: true
            - name: nix-store
              mountPath: /nix/store
              readOnly: true
            - name: nvidia0
              mountPath: /dev/nvidia0
            - name: nvidiactl
              mountPath: /dev/nvidiactl
            - name: nvidia-modeset
              mountPath: /dev/nvidia-modeset
            - name: nvidia-uvm
              mountPath: /dev/nvidia-uvm
            - name: nvidia-uvm-tools
              mountPath: /dev/nvidia-uvm-tools
            - name: nvidia-caps
              mountPath: /dev/nvidia-caps
      volumes:
        - name: kubelet-device-plugins-dir
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
        - name: nvidia-driver-root
          hostPath:
            path: /run/opengl-driver
            type: Directory
        - name: nix-store
          hostPath:
            path: /nix/store
            type: Directory
        - name: nvidia0
          hostPath:
            path: /dev/nvidia0
            type: CharDevice
        - name: nvidiactl
          hostPath:
            path: /dev/nvidiactl
            type: CharDevice
        - name: nvidia-modeset
          hostPath:
            path: /dev/nvidia-modeset
            type: CharDevice
        - name: nvidia-uvm
          hostPath:
            path: /dev/nvidia-uvm
            type: CharDevice
        - name: nvidia-uvm-tools
          hostPath:
            path: /dev/nvidia-uvm-tools
            type: CharDevice
        - name: nvidia-caps
          hostPath:
            path: /dev/nvidia-caps
            type: Directory
