// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package db

import (
	"context"
	"encoding/json"
)

const acquireClaim = `-- name: AcquireClaim :one
INSERT INTO claims (scope, resource_path, run_id, node, owner, ttl, expires_at, provenance)
VALUES ($1, $2, $3, $4, $5, $6::interval, now() + $6::interval, $7)
ON CONFLICT (scope, resource_path) WHERE state = 'active' DO NOTHING
RETURNING id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at
`

type AcquireClaimParams struct {
	Scope        string          `json:"scope"`
	ResourcePath string          `json:"resource_path"`
	RunID        string          `json:"run_id"`
	Node         string          `json:"node"`
	Owner        string          `json:"owner"`
	Column6      int64           `json:"column_6"`
	Provenance   json.RawMessage `json:"provenance"`
}

func (q *Queries) AcquireClaim(ctx context.Context, arg AcquireClaimParams) (Claim, error) {
	row := q.db.QueryRowContext(ctx, acquireClaim,
		arg.Scope,
		arg.ResourcePath,
		arg.RunID,
		arg.Node,
		arg.Owner,
		arg.Column6,
		arg.Provenance,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ResourcePath,
		&i.RunID,
		&i.Node,
		&i.Owner,
		&i.State,
		&i.Ttl,
		&i.ExpiresAt,
		&i.SuspendedAt,
		&i.ResumedAt,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimByID = `-- name: GetClaimByID :one
SELECT id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at FROM claims WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClaimByID(ctx context.Context, id string) (Claim, error) {
	row := q.db.QueryRowContext(ctx, getClaimByID, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ResourcePath,
		&i.RunID,
		&i.Node,
		&i.Owner,
		&i.State,
		&i.Ttl,
		&i.ExpiresAt,
		&i.SuspendedAt,
		&i.ResumedAt,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatClaim = `-- name: HeartbeatClaim :one
UPDATE claims
SET expires_at = now() + ttl::interval, updated_at = now()
WHERE id = $1 AND state = 'active' AND suspended_at IS NULL
RETURNING id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at
`

func (q *Queries) HeartbeatClaim(ctx context.Context, id string) (Claim, error) {
	row := q.db.QueryRowContext(ctx, heartbeatClaim, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ResourcePath,
		&i.RunID,
		&i.Node,
		&i.Owner,
		&i.State,
		&i.Ttl,
		&i.ExpiresAt,
		&i.SuspendedAt,
		&i.ResumedAt,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveClaimsByRun = `-- name: ListActiveClaimsByRun :many
SELECT id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at FROM claims WHERE run_id = $1 AND state = 'active'
`

func (q *Queries) ListActiveClaimsByRun(ctx context.Context, runID string) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listActiveClaimsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ResourcePath,
			&i.RunID,
			&i.Node,
			&i.Owner,
			&i.State,
			&i.Ttl,
			&i.ExpiresAt,
			&i.SuspendedAt,
			&i.ResumedAt,
			&i.Provenance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseClaim = `-- name: ReleaseClaim :one
UPDATE claims
SET state = 'released', expires_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at
`

func (q *Queries) ReleaseClaim(ctx context.Context, id string) (Claim, error) {
	row := q.db.QueryRowContext(ctx, releaseClaim, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ResourcePath,
		&i.RunID,
		&i.Node,
		&i.Owner,
		&i.State,
		&i.Ttl,
		&i.ExpiresAt,
		&i.SuspendedAt,
		&i.ResumedAt,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeAllClaims = `-- name: ResumeAllClaims :many
UPDATE claims
SET state = 'active',
    resumed_at = now(),
    expires_at = now() + (expires_at - suspended_at),
    suspended_at = NULL,
    updated_at = now()
WHERE state = 'suspended'
RETURNING id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at
`

func (q *Queries) ResumeAllClaims(ctx context.Context) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, resumeAllClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ResourcePath,
			&i.RunID,
			&i.Node,
			&i.Owner,
			&i.State,
			&i.Ttl,
			&i.ExpiresAt,
			&i.SuspendedAt,
			&i.ResumedAt,
			&i.Provenance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendAllClaims = `-- name: SuspendAllClaims :many
UPDATE claims
SET state = 'suspended', suspended_at = now(), updated_at = now()
WHERE state = 'active'
RETURNING id, scope, resource_path, run_id, node, owner, state, ttl, expires_at, suspended_at, resumed_at, provenance, created_at, updated_at
`

func (q *Queries) SuspendAllClaims(ctx context.Context) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, suspendAllClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ResourcePath,
			&i.RunID,
			&i.Node,
			&i.Owner,
			&i.State,
			&i.Ttl,
			&i.ExpiresAt,
			&i.SuspendedAt,
			&i.ResumedAt,
			&i.Provenance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
