// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
	"encoding/json"
)

const getEffectiveConfig = `-- name: GetEffectiveConfig :many
SELECT DISTINCT ON (key)
    layer, key, value, precedence, source
FROM config_projection
WHERE layer = 'global'
   OR (layer = 'project' AND project_id = $1)
   OR (layer = 'agent'   AND agent_id   = $2)
   OR (layer = 'node'    AND node_id    = $3)
   OR (layer = 'session' AND session_id = $4)
ORDER BY key, precedence DESC, updated_at DESC
`

type GetEffectiveConfigParams struct {
	ProjectID string `json:"project_id"`
	AgentID   string `json:"agent_id"`
	NodeID    string `json:"node_id"`
	SessionID string `json:"session_id"`
}

type GetEffectiveConfigRow struct {
	Layer      ConfigLayer     `json:"layer"`
	Key        string          `json:"key"`
	Value      json.RawMessage `json:"value"`
	Precedence int32           `json:"precedence"`
	Source     string          `json:"source"`
}

func (q *Queries) GetEffectiveConfig(ctx context.Context, arg GetEffectiveConfigParams) ([]GetEffectiveConfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getEffectiveConfig,
		arg.ProjectID,
		arg.AgentID,
		arg.NodeID,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEffectiveConfigRow
	for rows.Next() {
		var i GetEffectiveConfigRow
		if err := rows.Scan(
			&i.Layer,
			&i.Key,
			&i.Value,
			&i.Precedence,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO config_projection (
    layer, project_id, agent_id, node_id, session_id, key, value, precedence, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (layer, project_id, agent_id, node_id, session_id, key) DO UPDATE SET
    value = EXCLUDED.value,
    precedence = EXCLUDED.precedence,
    source = EXCLUDED.source,
    updated_at = now()
RETURNING id, layer, project_id, agent_id, node_id, session_id, key, value, precedence, source, created_at, updated_at
`

type UpsertConfigParams struct {
	Layer      ConfigLayer     `json:"layer"`
	ProjectID  string          `json:"project_id"`
	AgentID    string          `json:"agent_id"`
	NodeID     string          `json:"node_id"`
	SessionID  string          `json:"session_id"`
	Key        string          `json:"key"`
	Value      json.RawMessage `json:"value"`
	Precedence int32           `json:"precedence"`
	Source     string          `json:"source"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (ConfigProjection, error) {
	row := q.db.QueryRowContext(ctx, upsertConfig,
		arg.Layer,
		arg.ProjectID,
		arg.AgentID,
		arg.NodeID,
		arg.SessionID,
		arg.Key,
		arg.Value,
		arg.Precedence,
		arg.Source,
	)
	var i ConfigProjection
	err := row.Scan(
		&i.ID,
		&i.Layer,
		&i.ProjectID,
		&i.AgentID,
		&i.NodeID,
		&i.SessionID,
		&i.Key,
		&i.Value,
		&i.Precedence,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
