// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package db

import (
	"context"
	"encoding/json"
)

const getCapability = `-- name: GetCapability :one
SELECT id, kind, name, version, io, permissions, host_reqs, scorecard, lineage, latency, cost, safety, promotion_state, metadata, created_at, updated_at FROM capabilities WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCapability(ctx context.Context, id string) (Capability, error) {
	row := q.db.QueryRowContext(ctx, getCapability, id)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Version,
		&i.Io,
		&i.Permissions,
		&i.HostReqs,
		&i.Scorecard,
		&i.Lineage,
		&i.Latency,
		&i.Cost,
		&i.Safety,
		&i.PromotionState,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCapabilitiesByKind = `-- name: ListCapabilitiesByKind :many
SELECT id, kind, name, version, io, permissions, host_reqs, scorecard, lineage, latency, cost, safety, promotion_state, metadata, created_at, updated_at FROM capabilities WHERE kind = $1 ORDER BY name, version
`

func (q *Queries) ListCapabilitiesByKind(ctx context.Context, kind CapabilityKind) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilitiesByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Version,
			&i.Io,
			&i.Permissions,
			&i.HostReqs,
			&i.Scorecard,
			&i.Lineage,
			&i.Latency,
			&i.Cost,
			&i.Safety,
			&i.PromotionState,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilitiesByPromotionState = `-- name: ListCapabilitiesByPromotionState :many
SELECT id, kind, name, version, io, permissions, host_reqs, scorecard, lineage, latency, cost, safety, promotion_state, metadata, created_at, updated_at FROM capabilities WHERE promotion_state = $1 ORDER BY name
`

func (q *Queries) ListCapabilitiesByPromotionState(ctx context.Context, promotionState PromotionState) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilitiesByPromotionState, promotionState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Version,
			&i.Io,
			&i.Permissions,
			&i.HostReqs,
			&i.Scorecard,
			&i.Lineage,
			&i.Latency,
			&i.Cost,
			&i.Safety,
			&i.PromotionState,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCapability = `-- name: UpsertCapability :one
INSERT INTO capabilities (
    id, kind, name, version, io, permissions, host_reqs, scorecard, lineage,
    latency, cost, safety, promotion_state, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    kind = EXCLUDED.kind,
    name = EXCLUDED.name,
    version = EXCLUDED.version,
    io = EXCLUDED.io,
    permissions = EXCLUDED.permissions,
    host_reqs = EXCLUDED.host_reqs,
    scorecard = EXCLUDED.scorecard,
    lineage = EXCLUDED.lineage,
    latency = EXCLUDED.latency,
    cost = EXCLUDED.cost,
    safety = EXCLUDED.safety,
    promotion_state = EXCLUDED.promotion_state,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, kind, name, version, io, permissions, host_reqs, scorecard, lineage, latency, cost, safety, promotion_state, metadata, created_at, updated_at
`

type UpsertCapabilityParams struct {
	ID             string          `json:"id"`
	Kind           CapabilityKind  `json:"kind"`
	Name           string          `json:"name"`
	Version        string          `json:"version"`
	Io             json.RawMessage `json:"io"`
	Permissions    json.RawMessage `json:"permissions"`
	HostReqs       json.RawMessage `json:"host_reqs"`
	Scorecard      json.RawMessage `json:"scorecard"`
	Lineage        json.RawMessage `json:"lineage"`
	Latency        json.RawMessage `json:"latency"`
	Cost           json.RawMessage `json:"cost"`
	Safety         json.RawMessage `json:"safety"`
	PromotionState PromotionState  `json:"promotion_state"`
	Metadata       json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, upsertCapability,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Version,
		arg.Io,
		arg.Permissions,
		arg.HostReqs,
		arg.Scorecard,
		arg.Lineage,
		arg.Latency,
		arg.Cost,
		arg.Safety,
		arg.PromotionState,
		arg.Metadata,
	)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Version,
		&i.Io,
		&i.Permissions,
		&i.HostReqs,
		&i.Scorecard,
		&i.Lineage,
		&i.Latency,
		&i.Cost,
		&i.Safety,
		&i.PromotionState,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
