// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const completeJob = `-- name: CompleteJob :one
UPDATE jobs SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, queue, status, idempotency_key, envelope_key, payload, priority, attempts, max_attempts, leased_at, leased_by, scheduled_at, created_at, updated_at
`

type CompleteJobParams struct {
	ID     string    `json:"id"`
	Status JobStatus `json:"status"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, completeJob, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Status,
		&i.IdempotencyKey,
		&i.EnvelopeKey,
		&i.Payload,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeasedAt,
		&i.LeasedBy,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (queue, idempotency_key, envelope_key, payload, priority, max_attempts, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, now()))
ON CONFLICT (idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, queue, status, idempotency_key, envelope_key, payload, priority, attempts, max_attempts, leased_at, leased_by, scheduled_at, created_at, updated_at
`

type EnqueueJobParams struct {
	Queue          string          `json:"queue"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
	EnvelopeKey    string          `json:"envelope_key"`
	Payload        json.RawMessage `json:"payload"`
	Priority       int32           `json:"priority"`
	MaxAttempts    int32           `json:"max_attempts"`
	Column7        interface{}     `json:"column_7"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.Queue,
		arg.IdempotencyKey,
		arg.EnvelopeKey,
		arg.Payload,
		arg.Priority,
		arg.MaxAttempts,
		arg.Column7,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Status,
		&i.IdempotencyKey,
		&i.EnvelopeKey,
		&i.Payload,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeasedAt,
		&i.LeasedBy,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, queue, status, idempotency_key, envelope_key, payload, priority, attempts, max_attempts, leased_at, leased_by, scheduled_at, created_at, updated_at FROM jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Status,
		&i.IdempotencyKey,
		&i.EnvelopeKey,
		&i.Payload,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeasedAt,
		&i.LeasedBy,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseJob = `-- name: LeaseJob :one
WITH next_job AS (
    SELECT jobs.id FROM jobs
    WHERE jobs.queue = $1 AND jobs.status = 'pending' AND jobs.scheduled_at <= now()
    ORDER BY jobs.priority DESC, jobs.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs
SET status = 'leased', leased_at = now(), leased_by = $2, attempts = attempts + 1, updated_at = now()
WHERE jobs.id = (SELECT next_job.id FROM next_job)
RETURNING id, queue, status, idempotency_key, envelope_key, payload, priority, attempts, max_attempts, leased_at, leased_by, scheduled_at, created_at, updated_at
`

type LeaseJobParams struct {
	Queue    string         `json:"queue"`
	LeasedBy sql.NullString `json:"leased_by"`
}

func (q *Queries) LeaseJob(ctx context.Context, arg LeaseJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, leaseJob, arg.Queue, arg.LeasedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Status,
		&i.IdempotencyKey,
		&i.EnvelopeKey,
		&i.Payload,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeasedAt,
		&i.LeasedBy,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingJobsByQueue = `-- name: ListPendingJobsByQueue :many
SELECT id, queue, status, idempotency_key, envelope_key, payload, priority, attempts, max_attempts, leased_at, leased_by, scheduled_at, created_at, updated_at FROM jobs WHERE queue = $1 AND status = 'pending' ORDER BY priority DESC, created_at ASC
`

func (q *Queries) ListPendingJobsByQueue(ctx context.Context, queue string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobsByQueue, queue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Queue,
			&i.Status,
			&i.IdempotencyKey,
			&i.EnvelopeKey,
			&i.Payload,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LeasedAt,
			&i.LeasedBy,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
