// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type CanaryStage string

const (
	CanaryStageShadow CanaryStage = "shadow"
	CanaryStagePct1   CanaryStage = "pct_1"
	CanaryStagePct10  CanaryStage = "pct_10"
	CanaryStagePct100 CanaryStage = "pct_100"
)

func (e *CanaryStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CanaryStage(s)
	case string:
		*e = CanaryStage(s)
	default:
		return fmt.Errorf("unsupported scan type for CanaryStage: %T", src)
	}
	return nil
}

type NullCanaryStage struct {
	CanaryStage CanaryStage `json:"canary_stage"`
	Valid       bool        `json:"valid"` // Valid is true if CanaryStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCanaryStage) Scan(value interface{}) error {
	if value == nil {
		ns.CanaryStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CanaryStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCanaryStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CanaryStage), nil
}

type CapabilityKind string

const (
	CapabilityKindSkill     CapabilityKind = "skill"
	CapabilityKindPlugin    CapabilityKind = "plugin"
	CapabilityKindExtension CapabilityKind = "extension"
	CapabilityKindHook      CapabilityKind = "hook"
	CapabilityKindScript    CapabilityKind = "script"
	CapabilityKindModel     CapabilityKind = "model"
	CapabilityKindAdapter   CapabilityKind = "adapter"
)

func (e *CapabilityKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CapabilityKind(s)
	case string:
		*e = CapabilityKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CapabilityKind: %T", src)
	}
	return nil
}

type NullCapabilityKind struct {
	CapabilityKind CapabilityKind `json:"capability_kind"`
	Valid          bool           `json:"valid"` // Valid is true if CapabilityKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCapabilityKind) Scan(value interface{}) error {
	if value == nil {
		ns.CapabilityKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CapabilityKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCapabilityKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CapabilityKind), nil
}

type ClaimState string

const (
	ClaimStateActive    ClaimState = "active"
	ClaimStateReleased  ClaimState = "released"
	ClaimStateExpired   ClaimState = "expired"
	ClaimStateSuspended ClaimState = "suspended"
)

func (e *ClaimState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClaimState(s)
	case string:
		*e = ClaimState(s)
	default:
		return fmt.Errorf("unsupported scan type for ClaimState: %T", src)
	}
	return nil
}

type NullClaimState struct {
	ClaimState ClaimState `json:"claim_state"`
	Valid      bool       `json:"valid"` // Valid is true if ClaimState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClaimState) Scan(value interface{}) error {
	if value == nil {
		ns.ClaimState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClaimState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClaimState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClaimState), nil
}

type ConfigLayer string

const (
	ConfigLayerGlobal  ConfigLayer = "global"
	ConfigLayerProject ConfigLayer = "project"
	ConfigLayerAgent   ConfigLayer = "agent"
	ConfigLayerNode    ConfigLayer = "node"
	ConfigLayerSession ConfigLayer = "session"
)

func (e *ConfigLayer) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConfigLayer(s)
	case string:
		*e = ConfigLayer(s)
	default:
		return fmt.Errorf("unsupported scan type for ConfigLayer: %T", src)
	}
	return nil
}

type NullConfigLayer struct {
	ConfigLayer ConfigLayer `json:"config_layer"`
	Valid       bool        `json:"valid"` // Valid is true if ConfigLayer is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConfigLayer) Scan(value interface{}) error {
	if value == nil {
		ns.ConfigLayer, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConfigLayer.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConfigLayer) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConfigLayer), nil
}

type EvalStatus string

const (
	EvalStatusRunning EvalStatus = "running"
	EvalStatusPassed  EvalStatus = "passed"
	EvalStatusFailed  EvalStatus = "failed"
	EvalStatusAborted EvalStatus = "aborted"
)

func (e *EvalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvalStatus(s)
	case string:
		*e = EvalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EvalStatus: %T", src)
	}
	return nil
}

type NullEvalStatus struct {
	EvalStatus EvalStatus `json:"eval_status"`
	Valid      bool       `json:"valid"` // Valid is true if EvalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EvalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvalStatus), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusLeased    JobStatus = "leased"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
	JobStatusCancelled JobStatus = "cancelled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type PromotionState string

const (
	PromotionStateCandidate   PromotionState = "candidate"
	PromotionStateActive      PromotionState = "active"
	PromotionStateQuarantined PromotionState = "quarantined"
	PromotionStateRetired     PromotionState = "retired"
	PromotionStateRolledBack  PromotionState = "rolled_back"
)

func (e *PromotionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionState(s)
	case string:
		*e = PromotionState(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionState: %T", src)
	}
	return nil
}

type NullPromotionState struct {
	PromotionState PromotionState `json:"promotion_state"`
	Valid          bool           `json:"valid"` // Valid is true if PromotionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionState) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionState), nil
}

type RunStatusValue string

const (
	RunStatusValueUsefulResult    RunStatusValue = "useful_result"
	RunStatusValueNoArtifact      RunStatusValue = "no_artifact"
	RunStatusValueMissingEvidence RunStatusValue = "missing_evidence"
	RunStatusValueUnresolved      RunStatusValue = "unresolved"
	RunStatusValueBlocked         RunStatusValue = "blocked"
	RunStatusValueFailed          RunStatusValue = "failed"
	RunStatusValueReleased        RunStatusValue = "released"
	RunStatusValueExpired         RunStatusValue = "expired"
)

func (e *RunStatusValue) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatusValue(s)
	case string:
		*e = RunStatusValue(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatusValue: %T", src)
	}
	return nil
}

type NullRunStatusValue struct {
	RunStatusValue RunStatusValue `json:"run_status_value"`
	Valid          bool           `json:"valid"` // Valid is true if RunStatusValue is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatusValue) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatusValue, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatusValue.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatusValue) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatusValue), nil
}

type SourceClass string

const (
	SourceClassVerified SourceClass = "verified"
	SourceClassInferred SourceClass = "inferred"
)

func (e *SourceClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceClass(s)
	case string:
		*e = SourceClass(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceClass: %T", src)
	}
	return nil
}

type NullSourceClass struct {
	SourceClass SourceClass `json:"source_class"`
	Valid       bool        `json:"valid"` // Valid is true if SourceClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceClass) Scan(value interface{}) error {
	if value == nil {
		ns.SourceClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceClass), nil
}

type Adapter struct {
	ID             string          `json:"id"`
	CapabilityID   sql.NullString  `json:"capability_id"`
	BaseModel      string          `json:"base_model"`
	RoleBinding    sql.NullString  `json:"role_binding"`
	SkillBinding   sql.NullString  `json:"skill_binding"`
	AdapterPath    sql.NullString  `json:"adapter_path"`
	EvalRefs       json.RawMessage `json:"eval_refs"`
	PromotionState PromotionState  `json:"promotion_state"`
	Lineage        json.RawMessage `json:"lineage"`
	Metadata       json.RawMessage `json:"metadata"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type CanaryState struct {
	ID             string          `json:"id"`
	EvalRunID      string          `json:"eval_run_id"`
	CapabilityID   sql.NullString  `json:"capability_id"`
	Stage          CanaryStage     `json:"stage"`
	TrafficPercent int32           `json:"traffic_percent"`
	Gates          json.RawMessage `json:"gates"`
	Status         string          `json:"status"`
	StartedAt      time.Time       `json:"started_at"`
	FinishedAt     sql.NullTime    `json:"finished_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Capability struct {
	ID             string          `json:"id"`
	Kind           CapabilityKind  `json:"kind"`
	Name           string          `json:"name"`
	Version        string          `json:"version"`
	Io             json.RawMessage `json:"io"`
	Permissions    json.RawMessage `json:"permissions"`
	HostReqs       json.RawMessage `json:"host_reqs"`
	Scorecard      json.RawMessage `json:"scorecard"`
	Lineage        json.RawMessage `json:"lineage"`
	Latency        json.RawMessage `json:"latency"`
	Cost           json.RawMessage `json:"cost"`
	Safety         json.RawMessage `json:"safety"`
	PromotionState PromotionState  `json:"promotion_state"`
	Metadata       json.RawMessage `json:"metadata"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Claim struct {
	ID           string          `json:"id"`
	Scope        string          `json:"scope"`
	ResourcePath string          `json:"resource_path"`
	RunID        string          `json:"run_id"`
	Node         string          `json:"node"`
	Owner        string          `json:"owner"`
	State        ClaimState      `json:"state"`
	Ttl          int64           `json:"ttl"`
	ExpiresAt    time.Time       `json:"expires_at"`
	SuspendedAt  sql.NullTime    `json:"suspended_at"`
	ResumedAt    sql.NullTime    `json:"resumed_at"`
	Provenance   json.RawMessage `json:"provenance"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

// Effective config projected from config.yaml layers
type ConfigProjection struct {
	ID         string          `json:"id"`
	Layer      ConfigLayer     `json:"layer"`
	ProjectID  string          `json:"project_id"`
	AgentID    string          `json:"agent_id"`
	NodeID     string          `json:"node_id"`
	SessionID  string          `json:"session_id"`
	Key        string          `json:"key"`
	Value      json.RawMessage `json:"value"`
	Precedence int32           `json:"precedence"`
	Source     string          `json:"source"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type ConsolidationRun struct {
	ID             string          `json:"id"`
	SessionID      string          `json:"session_id"`
	RunID          sql.NullString  `json:"run_id"`
	CheckpointKind string          `json:"checkpoint_kind"`
	Reflection     json.RawMessage `json:"reflection"`
	Artifacts      json.RawMessage `json:"artifacts"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type EvalResult struct {
	ID         string         `json:"id"`
	EvalRunID  string         `json:"eval_run_id"`
	TestCaseID string         `json:"test_case_id"`
	Metric     string         `json:"metric"`
	Value      string         `json:"value"`
	Delta      sql.NullString `json:"delta"`
	Outcome    string         `json:"outcome"`
	Reviewer   sql.NullString `json:"reviewer"`
	CreatedAt  time.Time      `json:"created_at"`
}

type EvalRun struct {
	ID            string          `json:"id"`
	CandidateID   string          `json:"candidate_id"`
	CandidateKind string          `json:"candidate_kind"`
	BaselineID    sql.NullString  `json:"baseline_id"`
	Scorecard     json.RawMessage `json:"scorecard"`
	Status        EvalStatus      `json:"status"`
	StartedAt     time.Time       `json:"started_at"`
	FinishedAt    sql.NullTime    `json:"finished_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Job struct {
	ID             string          `json:"id"`
	Queue          string          `json:"queue"`
	Status         JobStatus       `json:"status"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
	EnvelopeKey    string          `json:"envelope_key"`
	Payload        json.RawMessage `json:"payload"`
	Priority       int32           `json:"priority"`
	Attempts       int32           `json:"attempts"`
	MaxAttempts    int32           `json:"max_attempts"`
	LeasedAt       sql.NullTime    `json:"leased_at"`
	LeasedBy       sql.NullString  `json:"leased_by"`
	ScheduledAt    time.Time       `json:"scheduled_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type JobDomain struct {
	ID         string          `json:"id"`
	JobID      string          `json:"job_id"`
	DomainKind string          `json:"domain_kind"`
	DomainID   string          `json:"domain_id"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
}

type MemoryEmbedding struct {
	ID          string         `json:"id"`
	AgentID     string         `json:"agent_id"`
	SessionID   sql.NullString `json:"session_id"`
	SourceClass SourceClass    `json:"source_class"`
	Hypothesis  bool           `json:"hypothesis"`
	Content     string         `json:"content"`
	// vector(1024) — dimension is provisional
	Embedding interface{}     `json:"embedding"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type ModelHealth struct {
	ID           string          `json:"id"`
	ModelRouteID string          `json:"model_route_id"`
	Node         string          `json:"node"`
	Status       string          `json:"status"`
	LatencyMs    sql.NullInt32   `json:"latency_ms"`
	LastCheck    sql.NullTime    `json:"last_check"`
	ErrorCount   int32           `json:"error_count"`
	Metadata     json.RawMessage `json:"metadata"`
	UpdatedAt    time.Time       `json:"updated_at"`
	CreatedAt    time.Time       `json:"created_at"`
}

type ModelRoute struct {
	ID              string          `json:"id"`
	ModelID         string          `json:"model_id"`
	Engine          string          `json:"engine"`
	DesiredReplicas int32           `json:"desired_replicas"`
	CurrentReplicas int32           `json:"current_replicas"`
	Active          bool            `json:"active"`
	Config          json.RawMessage `json:"config"`
	UpdatedAt       time.Time       `json:"updated_at"`
	CreatedAt       time.Time       `json:"created_at"`
}

type RunStatus struct {
	ID              string          `json:"id"`
	RunID           string          `json:"run_id"`
	SessionID       sql.NullString  `json:"session_id"`
	Status          RunStatusValue  `json:"status"`
	Artifacts       json.RawMessage `json:"artifacts"`
	Evidence        json.RawMessage `json:"evidence"`
	SourceSeparated json.RawMessage `json:"source_separated"`
	UpdatedAt       time.Time       `json:"updated_at"`
	CreatedAt       time.Time       `json:"created_at"`
}

type SyncManifest struct {
	ID        string          `json:"id"`
	Hash      string          `json:"hash"`
	Class     string          `json:"class"`
	SizeBytes int64           `json:"size_bytes"`
	Refs      json.RawMessage `json:"refs"`
	CreatedAt time.Time       `json:"created_at"`
}
