# Generated from agent_os/v1/registry.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import common_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from .common_pb import Fabric, Host, Model, Node, Provider


_ListModelsRequestFields: TypeAlias = Literal["fabric", "provider_id", "role"]

class ListModelsRequest(Message[_ListModelsRequestFields]):
    """
    ```proto
    message agent_os.v1.ListModelsRequest
    ```

    Attributes:
        fabric:
            Optional filters; empty means "all".

            ```proto
            agent_os.v1.Fabric fabric = 1;
            ```
        provider_id:
            ```proto
            string provider_id = 2;
            ```
        role:
            Optional role alias filter: general | coding | judge | embedding.

            ```proto
            string role = 3;
            ```
    """

    __slots__ = ("fabric", "provider_id", "role")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            fabric: Fabric | None = None,
            provider_id: str = "",
            role: str = "",
        ) -> None:
            pass

        fabric: Fabric
        provider_id: str
        role: str

_ListModelsResponseFields: TypeAlias = Literal["models"]

class ListModelsResponse(Message[_ListModelsResponseFields]):
    """
    ```proto
    message agent_os.v1.ListModelsResponse
    ```

    Attributes:
        models:
            ```proto
            repeated agent_os.v1.Model models = 1;
            ```
    """

    __slots__ = ("models",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            models: list[Model] | None = None,
        ) -> None:
            pass

        models: list[Model]

_ListProvidersRequestFields: TypeAlias = Literal["fabric"]

class ListProvidersRequest(Message[_ListProvidersRequestFields]):
    """
    ```proto
    message agent_os.v1.ListProvidersRequest
    ```

    Attributes:
        fabric:
            Optional fabric filter; FABRIC_UNSPECIFIED means "all".

            ```proto
            agent_os.v1.Fabric fabric = 1;
            ```
    """

    __slots__ = ("fabric",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            fabric: Fabric | None = None,
        ) -> None:
            pass

        fabric: Fabric

_ListProvidersResponseFields: TypeAlias = Literal["providers"]

class ListProvidersResponse(Message[_ListProvidersResponseFields]):
    """
    ```proto
    message agent_os.v1.ListProvidersResponse
    ```

    Attributes:
        providers:
            ```proto
            repeated agent_os.v1.Provider providers = 1;
            ```
    """

    __slots__ = ("providers",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            providers: list[Provider] | None = None,
        ) -> None:
            pass

        providers: list[Provider]

_ListHostsRequestFields: TypeAlias = NoReturn

class ListHostsRequest(Message[_ListHostsRequestFields]):
    """
    ```proto
    message agent_os.v1.ListHostsRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_ListHostsResponseFields: TypeAlias = Literal["hosts"]

class ListHostsResponse(Message[_ListHostsResponseFields]):
    """
    ```proto
    message agent_os.v1.ListHostsResponse
    ```

    Attributes:
        hosts:
            ```proto
            repeated agent_os.v1.Host hosts = 1;
            ```
    """

    __slots__ = ("hosts",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            hosts: list[Host] | None = None,
        ) -> None:
            pass

        hosts: list[Host]

_ListNodesRequestFields: TypeAlias = NoReturn

class ListNodesRequest(Message[_ListNodesRequestFields]):
    """
    ```proto
    message agent_os.v1.ListNodesRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_ListNodesResponseFields: TypeAlias = Literal["nodes"]

class ListNodesResponse(Message[_ListNodesResponseFields]):
    """
    ```proto
    message agent_os.v1.ListNodesResponse
    ```

    Attributes:
        nodes:
            ```proto
            repeated agent_os.v1.Node nodes = 1;
            ```
    """

    __slots__ = ("nodes",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            nodes: list[Node] | None = None,
        ) -> None:
            pass

        nodes: list[Node]


_DESC = file_desc(
    b'\n\x1aagent_os/v1/registry.proto\x12\x0bagent_os.v1\x1a\x18agent_os/v1/common.proto"u\n\x11ListModelsRequest\x12+\n\x06fabric\x18\x01 \x01(\x0e2\x13.agent_os.v1.FabricR\x06fabric\x12\x1f\n\x0bprovider_id\x18\x02 \x01(\tR\nproviderId\x12\x12\n\x04role\x18\x03 \x01(\tR\x04role"@\n\x12ListModelsResponse\x12*\n\x06models\x18\x01 \x03(\x0b2\x12.agent_os.v1.ModelR\x06models"C\n\x14ListProvidersRequest\x12+\n\x06fabric\x18\x01 \x01(\x0e2\x13.agent_os.v1.FabricR\x06fabric"L\n\x15ListProvidersResponse\x123\n\tproviders\x18\x01 \x03(\x0b2\x15.agent_os.v1.ProviderR\tproviders"\x12\n\x10ListHostsRequest"<\n\x11ListHostsResponse\x12\'\n\x05hosts\x18\x01 \x03(\x0b2\x11.agent_os.v1.HostR\x05hosts"\x12\n\x10ListNodesRequest"<\n\x11ListNodesResponse\x12\'\n\x05nodes\x18\x01 \x03(\x0b2\x11.agent_os.v1.NodeR\x05nodes2\xd0\x02\n\x0fRegistryService\x12M\n\nListModels\x12\x1e.agent_os.v1.ListModelsRequest\x1a\x1f.agent_os.v1.ListModelsResponse\x12V\n\rListProviders\x12!.agent_os.v1.ListProvidersRequest\x1a".agent_os.v1.ListProvidersResponse\x12J\n\tListHosts\x12\x1d.agent_os.v1.ListHostsRequest\x1a\x1e.agent_os.v1.ListHostsResponse\x12J\n\tListNodes\x12\x1d.agent_os.v1.ListNodesRequest\x1a\x1e.agent_os.v1.ListNodesResponseb\x06proto3',
    [
        common_pb.desc(),
    ],
    {
        "ListModelsRequest": ListModelsRequest,
        "ListModelsResponse": ListModelsResponse,
        "ListProvidersRequest": ListProvidersRequest,
        "ListProvidersResponse": ListProvidersResponse,
        "ListHostsRequest": ListHostsRequest,
        "ListHostsResponse": ListHostsResponse,
        "ListNodesRequest": ListNodesRequest,
        "ListNodesResponse": ListNodesResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `agent_os/v1/registry.proto`."""
    return _DESC
