# Generated from agent_os/v1/switchers.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .switchers_pb import GetSwitcherStateRequest, GetSwitcherStateResponse, ListSwitcherOptionsRequest, ListSwitcherOptionsResponse, SetSwitcherRequest, SetSwitcherResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class SwitcherService(Protocol):
    async def get_switcher_state(self, request: GetSwitcherStateRequest, ctx: RequestContext[GetSwitcherStateRequest, GetSwitcherStateResponse]) -> GetSwitcherStateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def set_switcher(self, request: SetSwitcherRequest, ctx: RequestContext[SetSwitcherRequest, SetSwitcherResponse]) -> SetSwitcherResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_switcher_options(self, request: ListSwitcherOptionsRequest, ctx: RequestContext[ListSwitcherOptionsRequest, ListSwitcherOptionsResponse]) -> ListSwitcherOptionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class SwitcherServiceASGIApplication(ConnectASGIApplication[SwitcherService]):
    def __init__(
        self,
        service: SwitcherService | AsyncGenerator[SwitcherService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/agent_os.v1.SwitcherService/GetSwitcherState": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSwitcherState",
                        service_name="agent_os.v1.SwitcherService",
                        input=GetSwitcherStateRequest,
                        output=GetSwitcherStateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_switcher_state,
                ),
                "/agent_os.v1.SwitcherService/SetSwitcher": Endpoint.unary(
                    method=MethodInfo(
                        name="SetSwitcher",
                        service_name="agent_os.v1.SwitcherService",
                        input=SetSwitcherRequest,
                        output=SetSwitcherResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.set_switcher,
                ),
                "/agent_os.v1.SwitcherService/ListSwitcherOptions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSwitcherOptions",
                        service_name="agent_os.v1.SwitcherService",
                        input=ListSwitcherOptionsRequest,
                        output=ListSwitcherOptionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_switcher_options,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.SwitcherService"


class SwitcherServiceClient(ConnectClient):
    async def get_switcher_state(
        self,
        request: GetSwitcherStateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetSwitcherStateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSwitcherState",
                service_name="agent_os.v1.SwitcherService",
                input=GetSwitcherStateRequest,
                output=GetSwitcherStateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_switcher(
        self,
        request: SetSwitcherRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SetSwitcherResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetSwitcher",
                service_name="agent_os.v1.SwitcherService",
                input=SetSwitcherRequest,
                output=SetSwitcherResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_switcher_options(
        self,
        request: ListSwitcherOptionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListSwitcherOptionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSwitcherOptions",
                service_name="agent_os.v1.SwitcherService",
                input=ListSwitcherOptionsRequest,
                output=ListSwitcherOptionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class SwitcherServiceSync(Protocol):
    def get_switcher_state(self, request: GetSwitcherStateRequest, ctx: RequestContext[GetSwitcherStateRequest, GetSwitcherStateResponse]) -> GetSwitcherStateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def set_switcher(self, request: SetSwitcherRequest, ctx: RequestContext[SetSwitcherRequest, SetSwitcherResponse]) -> SetSwitcherResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_switcher_options(self, request: ListSwitcherOptionsRequest, ctx: RequestContext[ListSwitcherOptionsRequest, ListSwitcherOptionsResponse]) -> ListSwitcherOptionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class SwitcherServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: SwitcherServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_os.v1.SwitcherService/GetSwitcherState": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSwitcherState",
                        service_name="agent_os.v1.SwitcherService",
                        input=GetSwitcherStateRequest,
                        output=GetSwitcherStateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_switcher_state,
                ),
                "/agent_os.v1.SwitcherService/SetSwitcher": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetSwitcher",
                        service_name="agent_os.v1.SwitcherService",
                        input=SetSwitcherRequest,
                        output=SetSwitcherResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.set_switcher,
                ),
                "/agent_os.v1.SwitcherService/ListSwitcherOptions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSwitcherOptions",
                        service_name="agent_os.v1.SwitcherService",
                        input=ListSwitcherOptionsRequest,
                        output=ListSwitcherOptionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_switcher_options,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.SwitcherService"


class SwitcherServiceClientSync(ConnectClientSync):
    def get_switcher_state(
        self,
        request: GetSwitcherStateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetSwitcherStateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSwitcherState",
                service_name="agent_os.v1.SwitcherService",
                input=GetSwitcherStateRequest,
                output=GetSwitcherStateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def set_switcher(
        self,
        request: SetSwitcherRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SetSwitcherResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetSwitcher",
                service_name="agent_os.v1.SwitcherService",
                input=SetSwitcherRequest,
                output=SetSwitcherResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_switcher_options(
        self,
        request: ListSwitcherOptionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListSwitcherOptionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSwitcherOptions",
                service_name="agent_os.v1.SwitcherService",
                input=ListSwitcherOptionsRequest,
                output=ListSwitcherOptionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
