# Generated from andromeda/v1/jobs.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .jobs_pb import GetDomainStatusRequest, GetDomainStatusResponse, GetJobStatusRequest, GetJobStatusResponse, ListDomainsRequest, ListDomainsResponse, ListJobsRequest, ListJobsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class JobService(Protocol):
    async def list_jobs(self, request: ListJobsRequest, ctx: RequestContext[ListJobsRequest, ListJobsResponse]) -> ListJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_job_status(self, request: GetJobStatusRequest, ctx: RequestContext[GetJobStatusRequest, GetJobStatusResponse]) -> GetJobStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class JobServiceASGIApplication(ConnectASGIApplication[JobService]):
    def __init__(
        self,
        service: JobService | AsyncGenerator[JobService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/andromeda.v1.JobService/ListJobs": Endpoint.unary(
                    method=MethodInfo(
                        name="ListJobs",
                        service_name="andromeda.v1.JobService",
                        input=ListJobsRequest,
                        output=ListJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_jobs,
                ),
                "/andromeda.v1.JobService/GetJobStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="andromeda.v1.JobService",
                        input=GetJobStatusRequest,
                        output=GetJobStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/andromeda.v1.JobService"


class JobServiceClient(ConnectClient):
    async def list_jobs(
        self,
        request: ListJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListJobsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListJobs",
                service_name="andromeda.v1.JobService",
                input=ListJobsRequest,
                output=ListJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job_status(
        self,
        request: GetJobStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetJobStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="andromeda.v1.JobService",
                input=GetJobStatusRequest,
                output=GetJobStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class JobServiceSync(Protocol):
    def list_jobs(self, request: ListJobsRequest, ctx: RequestContext[ListJobsRequest, ListJobsResponse]) -> ListJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_job_status(self, request: GetJobStatusRequest, ctx: RequestContext[GetJobStatusRequest, GetJobStatusResponse]) -> GetJobStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class JobServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: JobServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/andromeda.v1.JobService/ListJobs": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListJobs",
                        service_name="andromeda.v1.JobService",
                        input=ListJobsRequest,
                        output=ListJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_jobs,
                ),
                "/andromeda.v1.JobService/GetJobStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="andromeda.v1.JobService",
                        input=GetJobStatusRequest,
                        output=GetJobStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/andromeda.v1.JobService"


class JobServiceClientSync(ConnectClientSync):
    def list_jobs(
        self,
        request: ListJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListJobsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListJobs",
                service_name="andromeda.v1.JobService",
                input=ListJobsRequest,
                output=ListJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_job_status(
        self,
        request: GetJobStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetJobStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="andromeda.v1.JobService",
                input=GetJobStatusRequest,
                output=GetJobStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class DomainService(Protocol):
    async def list_domains(self, request: ListDomainsRequest, ctx: RequestContext[ListDomainsRequest, ListDomainsResponse]) -> ListDomainsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_domain_status(self, request: GetDomainStatusRequest, ctx: RequestContext[GetDomainStatusRequest, GetDomainStatusResponse]) -> GetDomainStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class DomainServiceASGIApplication(ConnectASGIApplication[DomainService]):
    def __init__(
        self,
        service: DomainService | AsyncGenerator[DomainService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/andromeda.v1.DomainService/ListDomains": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDomains",
                        service_name="andromeda.v1.DomainService",
                        input=ListDomainsRequest,
                        output=ListDomainsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_domains,
                ),
                "/andromeda.v1.DomainService/GetDomainStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDomainStatus",
                        service_name="andromeda.v1.DomainService",
                        input=GetDomainStatusRequest,
                        output=GetDomainStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_domain_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/andromeda.v1.DomainService"


class DomainServiceClient(ConnectClient):
    async def list_domains(
        self,
        request: ListDomainsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDomainsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDomains",
                service_name="andromeda.v1.DomainService",
                input=ListDomainsRequest,
                output=ListDomainsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_domain_status(
        self,
        request: GetDomainStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetDomainStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDomainStatus",
                service_name="andromeda.v1.DomainService",
                input=GetDomainStatusRequest,
                output=GetDomainStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class DomainServiceSync(Protocol):
    def list_domains(self, request: ListDomainsRequest, ctx: RequestContext[ListDomainsRequest, ListDomainsResponse]) -> ListDomainsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_domain_status(self, request: GetDomainStatusRequest, ctx: RequestContext[GetDomainStatusRequest, GetDomainStatusResponse]) -> GetDomainStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class DomainServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: DomainServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/andromeda.v1.DomainService/ListDomains": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDomains",
                        service_name="andromeda.v1.DomainService",
                        input=ListDomainsRequest,
                        output=ListDomainsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_domains,
                ),
                "/andromeda.v1.DomainService/GetDomainStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDomainStatus",
                        service_name="andromeda.v1.DomainService",
                        input=GetDomainStatusRequest,
                        output=GetDomainStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_domain_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/andromeda.v1.DomainService"


class DomainServiceClientSync(ConnectClientSync):
    def list_domains(
        self,
        request: ListDomainsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDomainsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDomains",
                service_name="andromeda.v1.DomainService",
                input=ListDomainsRequest,
                output=ListDomainsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_domain_status(
        self,
        request: GetDomainStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetDomainStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDomainStatus",
                service_name="andromeda.v1.DomainService",
                input=GetDomainStatusRequest,
                output=GetDomainStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
