# Generated from andromeda/v1/registry.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import common_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from .common_pb import Fabric, Host, Model, Node, Provider


_ListModelsRequestFields: TypeAlias = Literal["fabric", "provider_id", "role"]

class ListModelsRequest(Message[_ListModelsRequestFields]):
    """
    ```proto
    message andromeda.v1.ListModelsRequest
    ```

    Attributes:
        fabric:
            Optional filters; empty means "all".

            ```proto
            andromeda.v1.Fabric fabric = 1;
            ```
        provider_id:
            ```proto
            string provider_id = 2;
            ```
        role:
            Optional role alias filter: general | coding | judge | embedding.

            ```proto
            string role = 3;
            ```
    """

    __slots__ = ("fabric", "provider_id", "role")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            fabric: Fabric | None = None,
            provider_id: str = "",
            role: str = "",
        ) -> None:
            pass

        fabric: Fabric
        provider_id: str
        role: str

_ListModelsResponseFields: TypeAlias = Literal["models"]

class ListModelsResponse(Message[_ListModelsResponseFields]):
    """
    ```proto
    message andromeda.v1.ListModelsResponse
    ```

    Attributes:
        models:
            ```proto
            repeated andromeda.v1.Model models = 1;
            ```
    """

    __slots__ = ("models",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            models: list[Model] | None = None,
        ) -> None:
            pass

        models: list[Model]

_ListProvidersRequestFields: TypeAlias = Literal["fabric"]

class ListProvidersRequest(Message[_ListProvidersRequestFields]):
    """
    ```proto
    message andromeda.v1.ListProvidersRequest
    ```

    Attributes:
        fabric:
            Optional fabric filter; FABRIC_UNSPECIFIED means "all".

            ```proto
            andromeda.v1.Fabric fabric = 1;
            ```
    """

    __slots__ = ("fabric",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            fabric: Fabric | None = None,
        ) -> None:
            pass

        fabric: Fabric

_ListProvidersResponseFields: TypeAlias = Literal["providers"]

class ListProvidersResponse(Message[_ListProvidersResponseFields]):
    """
    ```proto
    message andromeda.v1.ListProvidersResponse
    ```

    Attributes:
        providers:
            ```proto
            repeated andromeda.v1.Provider providers = 1;
            ```
    """

    __slots__ = ("providers",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            providers: list[Provider] | None = None,
        ) -> None:
            pass

        providers: list[Provider]

_ListHostsRequestFields: TypeAlias = NoReturn

class ListHostsRequest(Message[_ListHostsRequestFields]):
    """
    ```proto
    message andromeda.v1.ListHostsRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_ListHostsResponseFields: TypeAlias = Literal["hosts"]

class ListHostsResponse(Message[_ListHostsResponseFields]):
    """
    ```proto
    message andromeda.v1.ListHostsResponse
    ```

    Attributes:
        hosts:
            ```proto
            repeated andromeda.v1.Host hosts = 1;
            ```
    """

    __slots__ = ("hosts",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            hosts: list[Host] | None = None,
        ) -> None:
            pass

        hosts: list[Host]

_ListNodesRequestFields: TypeAlias = NoReturn

class ListNodesRequest(Message[_ListNodesRequestFields]):
    """
    ```proto
    message andromeda.v1.ListNodesRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_ListNodesResponseFields: TypeAlias = Literal["nodes"]

class ListNodesResponse(Message[_ListNodesResponseFields]):
    """
    ```proto
    message andromeda.v1.ListNodesResponse
    ```

    Attributes:
        nodes:
            ```proto
            repeated andromeda.v1.Node nodes = 1;
            ```
    """

    __slots__ = ("nodes",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            nodes: list[Node] | None = None,
        ) -> None:
            pass

        nodes: list[Node]


_DESC = file_desc(
    b'\n\x1bandromeda/v1/registry.proto\x12\x0candromeda.v1\x1a\x19andromeda/v1/common.proto"v\n\x11ListModelsRequest\x12,\n\x06fabric\x18\x01 \x01(\x0e2\x14.andromeda.v1.FabricR\x06fabric\x12\x1f\n\x0bprovider_id\x18\x02 \x01(\tR\nproviderId\x12\x12\n\x04role\x18\x03 \x01(\tR\x04role"A\n\x12ListModelsResponse\x12+\n\x06models\x18\x01 \x03(\x0b2\x13.andromeda.v1.ModelR\x06models"D\n\x14ListProvidersRequest\x12,\n\x06fabric\x18\x01 \x01(\x0e2\x14.andromeda.v1.FabricR\x06fabric"M\n\x15ListProvidersResponse\x124\n\tproviders\x18\x01 \x03(\x0b2\x16.andromeda.v1.ProviderR\tproviders"\x12\n\x10ListHostsRequest"=\n\x11ListHostsResponse\x12(\n\x05hosts\x18\x01 \x03(\x0b2\x12.andromeda.v1.HostR\x05hosts"\x12\n\x10ListNodesRequest"=\n\x11ListNodesResponse\x12(\n\x05nodes\x18\x01 \x03(\x0b2\x12.andromeda.v1.NodeR\x05nodes2\xd8\x02\n\x0fRegistryService\x12O\n\nListModels\x12\x1f.andromeda.v1.ListModelsRequest\x1a .andromeda.v1.ListModelsResponse\x12X\n\rListProviders\x12".andromeda.v1.ListProvidersRequest\x1a#.andromeda.v1.ListProvidersResponse\x12L\n\tListHosts\x12\x1e.andromeda.v1.ListHostsRequest\x1a\x1f.andromeda.v1.ListHostsResponse\x12L\n\tListNodes\x12\x1e.andromeda.v1.ListNodesRequest\x1a\x1f.andromeda.v1.ListNodesResponseb\x06proto3',
    [
        common_pb.desc(),
    ],
    {
        "ListModelsRequest": ListModelsRequest,
        "ListModelsResponse": ListModelsResponse,
        "ListProvidersRequest": ListProvidersRequest,
        "ListProvidersResponse": ListProvidersResponse,
        "ListHostsRequest": ListHostsRequest,
        "ListHostsResponse": ListHostsResponse,
        "ListNodesRequest": ListNodesRequest,
        "ListNodesResponse": ListNodesResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `andromeda/v1/registry.proto`."""
    return _DESC
