# Generated from agent_os/v1/health.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .health_pb import GetHealthRequest, GetHealthResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class HealthService(Protocol):
    async def get_health(self, request: GetHealthRequest, ctx: RequestContext[GetHealthRequest, GetHealthResponse]) -> GetHealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class HealthServiceASGIApplication(ConnectASGIApplication[HealthService]):
    def __init__(
        self,
        service: HealthService | AsyncGenerator[HealthService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/agent_os.v1.HealthService/GetHealth": Endpoint.unary(
                    method=MethodInfo(
                        name="GetHealth",
                        service_name="agent_os.v1.HealthService",
                        input=GetHealthRequest,
                        output=GetHealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_health,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.HealthService"


class HealthServiceClient(ConnectClient):
    async def get_health(
        self,
        request: GetHealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetHealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetHealth",
                service_name="agent_os.v1.HealthService",
                input=GetHealthRequest,
                output=GetHealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class HealthServiceSync(Protocol):
    def get_health(self, request: GetHealthRequest, ctx: RequestContext[GetHealthRequest, GetHealthResponse]) -> GetHealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class HealthServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: HealthServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_os.v1.HealthService/GetHealth": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetHealth",
                        service_name="agent_os.v1.HealthService",
                        input=GetHealthRequest,
                        output=GetHealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_health,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.HealthService"


class HealthServiceClientSync(ConnectClientSync):
    def get_health(
        self,
        request: GetHealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GetHealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetHealth",
                service_name="agent_os.v1.HealthService",
                input=GetHealthRequest,
                output=GetHealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
