# Generated from agent_os/v1/health.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import common_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from .common_pb import Node, Usage


_GetHealthRequestFields: TypeAlias = NoReturn

class GetHealthRequest(Message[_GetHealthRequestFields]):
    """
    ```proto
    message agent_os.v1.GetHealthRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_ComponentHealthFields: TypeAlias = Literal["name", "state", "detail"]

class ComponentHealth(Message[_ComponentHealthFields]):
    """
    The health of one named subsystem (gateway / postgres / nats / engine / ...).

    ```proto
    message agent_os.v1.ComponentHealth
    ```

    Attributes:
        name:
            ```proto
            string name = 1;
            ```
        state:
            ok | degraded | down.

            ```proto
            string state = 2;
            ```
        detail:
            ```proto
            string detail = 3;
            ```
    """

    __slots__ = ("name", "state", "detail")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            name: str = "",
            state: str = "",
            detail: str = "",
        ) -> None:
            pass

        name: str
        state: str
        detail: str

_GetHealthResponseFields: TypeAlias = Literal["paused", "nodes", "components", "usage"]

class GetHealthResponse(Message[_GetHealthResponseFields]):
    """
    ```proto
    message agent_os.v1.GetHealthResponse
    ```

    Attributes:
        paused:
            True when the system is paused under require-all-nodes (a server is down,
            §00 S4 / D-020). Clients render a paused banner; turn dispatch is gated.

            ```proto
            bool paused = 1;
            ```
        nodes:
            ```proto
            repeated agent_os.v1.Node nodes = 2;
            ```
        components:
            ```proto
            repeated agent_os.v1.ComponentHealth components = 3;
            ```
        usage:
            Aggregate usage/budget rollup (degrade-to-local indicator, §01 G6).

            ```proto
            optional agent_os.v1.Usage usage = 4;
            ```
    """

    __slots__ = ("paused", "nodes", "components", "usage")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            paused: bool = False,
            nodes: list[Node] | None = None,
            components: list[ComponentHealth] | None = None,
            usage: Usage | None = None,
        ) -> None:
            pass

        paused: bool
        nodes: list[Node]
        components: list[ComponentHealth]
        usage: Usage | None


_DESC = file_desc(
    b'\n\x18agent_os/v1/health.proto\x12\x0bagent_os.v1\x1a\x18agent_os/v1/common.proto"\x12\n\x10GetHealthRequest"S\n\x0fComponentHealth\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n\x06detail\x18\x03 \x01(\tR\x06detail"\xbc\x01\n\x11GetHealthResponse\x12\x16\n\x06paused\x18\x01 \x01(\x08R\x06paused\x12\'\n\x05nodes\x18\x02 \x03(\x0b2\x11.agent_os.v1.NodeR\x05nodes\x12<\n\ncomponents\x18\x03 \x03(\x0b2\x1c.agent_os.v1.ComponentHealthR\ncomponents\x12(\n\x05usage\x18\x04 \x01(\x0b2\x12.agent_os.v1.UsageR\x05usage2[\n\rHealthService\x12J\n\tGetHealth\x12\x1d.agent_os.v1.GetHealthRequest\x1a\x1e.agent_os.v1.GetHealthResponseb\x06proto3',
    [
        common_pb.desc(),
    ],
    {
        "GetHealthRequest": GetHealthRequest,
        "ComponentHealth": ComponentHealth,
        "GetHealthResponse": GetHealthResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `agent_os/v1/health.proto`."""
    return _DESC
