# Generated from agent_os/v1/registry.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .registry_pb import ListHostsRequest, ListHostsResponse, ListModelsRequest, ListModelsResponse, ListNodesRequest, ListNodesResponse, ListProvidersRequest, ListProvidersResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class RegistryService(Protocol):
    async def list_models(self, request: ListModelsRequest, ctx: RequestContext[ListModelsRequest, ListModelsResponse]) -> ListModelsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_providers(self, request: ListProvidersRequest, ctx: RequestContext[ListProvidersRequest, ListProvidersResponse]) -> ListProvidersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_hosts(self, request: ListHostsRequest, ctx: RequestContext[ListHostsRequest, ListHostsResponse]) -> ListHostsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_nodes(self, request: ListNodesRequest, ctx: RequestContext[ListNodesRequest, ListNodesResponse]) -> ListNodesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RegistryServiceASGIApplication(ConnectASGIApplication[RegistryService]):
    def __init__(
        self,
        service: RegistryService | AsyncGenerator[RegistryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/agent_os.v1.RegistryService/ListModels": Endpoint.unary(
                    method=MethodInfo(
                        name="ListModels",
                        service_name="agent_os.v1.RegistryService",
                        input=ListModelsRequest,
                        output=ListModelsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_models,
                ),
                "/agent_os.v1.RegistryService/ListProviders": Endpoint.unary(
                    method=MethodInfo(
                        name="ListProviders",
                        service_name="agent_os.v1.RegistryService",
                        input=ListProvidersRequest,
                        output=ListProvidersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_providers,
                ),
                "/agent_os.v1.RegistryService/ListHosts": Endpoint.unary(
                    method=MethodInfo(
                        name="ListHosts",
                        service_name="agent_os.v1.RegistryService",
                        input=ListHostsRequest,
                        output=ListHostsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_hosts,
                ),
                "/agent_os.v1.RegistryService/ListNodes": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNodes",
                        service_name="agent_os.v1.RegistryService",
                        input=ListNodesRequest,
                        output=ListNodesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_nodes,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.RegistryService"


class RegistryServiceClient(ConnectClient):
    async def list_models(
        self,
        request: ListModelsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListModelsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListModels",
                service_name="agent_os.v1.RegistryService",
                input=ListModelsRequest,
                output=ListModelsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_providers(
        self,
        request: ListProvidersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListProvidersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProviders",
                service_name="agent_os.v1.RegistryService",
                input=ListProvidersRequest,
                output=ListProvidersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_hosts(
        self,
        request: ListHostsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListHostsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListHosts",
                service_name="agent_os.v1.RegistryService",
                input=ListHostsRequest,
                output=ListHostsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_nodes(
        self,
        request: ListNodesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListNodesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNodes",
                service_name="agent_os.v1.RegistryService",
                input=ListNodesRequest,
                output=ListNodesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class RegistryServiceSync(Protocol):
    def list_models(self, request: ListModelsRequest, ctx: RequestContext[ListModelsRequest, ListModelsResponse]) -> ListModelsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_providers(self, request: ListProvidersRequest, ctx: RequestContext[ListProvidersRequest, ListProvidersResponse]) -> ListProvidersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_hosts(self, request: ListHostsRequest, ctx: RequestContext[ListHostsRequest, ListHostsResponse]) -> ListHostsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_nodes(self, request: ListNodesRequest, ctx: RequestContext[ListNodesRequest, ListNodesResponse]) -> ListNodesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class RegistryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: RegistryServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_os.v1.RegistryService/ListModels": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListModels",
                        service_name="agent_os.v1.RegistryService",
                        input=ListModelsRequest,
                        output=ListModelsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_models,
                ),
                "/agent_os.v1.RegistryService/ListProviders": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListProviders",
                        service_name="agent_os.v1.RegistryService",
                        input=ListProvidersRequest,
                        output=ListProvidersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_providers,
                ),
                "/agent_os.v1.RegistryService/ListHosts": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListHosts",
                        service_name="agent_os.v1.RegistryService",
                        input=ListHostsRequest,
                        output=ListHostsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_hosts,
                ),
                "/agent_os.v1.RegistryService/ListNodes": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNodes",
                        service_name="agent_os.v1.RegistryService",
                        input=ListNodesRequest,
                        output=ListNodesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_nodes,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.RegistryService"


class RegistryServiceClientSync(ConnectClientSync):
    def list_models(
        self,
        request: ListModelsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListModelsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListModels",
                service_name="agent_os.v1.RegistryService",
                input=ListModelsRequest,
                output=ListModelsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_providers(
        self,
        request: ListProvidersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListProvidersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProviders",
                service_name="agent_os.v1.RegistryService",
                input=ListProvidersRequest,
                output=ListProvidersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_hosts(
        self,
        request: ListHostsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListHostsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListHosts",
                service_name="agent_os.v1.RegistryService",
                input=ListHostsRequest,
                output=ListHostsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_nodes(
        self,
        request: ListNodesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListNodesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNodes",
                service_name="agent_os.v1.RegistryService",
                input=ListNodesRequest,
                output=ListNodesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
