# Generated from agent_os/v1/sessions.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .sessions_pb import AttachSessionRequest, AttachSessionResponse, CreateSessionRequest, CreateSessionResponse, ForkSessionRequest, ForkSessionResponse, ListSessionsRequest, ListSessionsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class SessionService(Protocol):
    async def create_session(self, request: CreateSessionRequest, ctx: RequestContext[CreateSessionRequest, CreateSessionResponse]) -> CreateSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_sessions(self, request: ListSessionsRequest, ctx: RequestContext[ListSessionsRequest, ListSessionsResponse]) -> ListSessionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def attach_session(self, request: AttachSessionRequest, ctx: RequestContext[AttachSessionRequest, AttachSessionResponse]) -> AttachSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def fork_session(self, request: ForkSessionRequest, ctx: RequestContext[ForkSessionRequest, ForkSessionResponse]) -> ForkSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class SessionServiceASGIApplication(ConnectASGIApplication[SessionService]):
    def __init__(
        self,
        service: SessionService | AsyncGenerator[SessionService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/agent_os.v1.SessionService/CreateSession": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateSession",
                        service_name="agent_os.v1.SessionService",
                        input=CreateSessionRequest,
                        output=CreateSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_session,
                ),
                "/agent_os.v1.SessionService/ListSessions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSessions",
                        service_name="agent_os.v1.SessionService",
                        input=ListSessionsRequest,
                        output=ListSessionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_sessions,
                ),
                "/agent_os.v1.SessionService/AttachSession": Endpoint.unary(
                    method=MethodInfo(
                        name="AttachSession",
                        service_name="agent_os.v1.SessionService",
                        input=AttachSessionRequest,
                        output=AttachSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.attach_session,
                ),
                "/agent_os.v1.SessionService/ForkSession": Endpoint.unary(
                    method=MethodInfo(
                        name="ForkSession",
                        service_name="agent_os.v1.SessionService",
                        input=ForkSessionRequest,
                        output=ForkSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.fork_session,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.SessionService"


class SessionServiceClient(ConnectClient):
    async def create_session(
        self,
        request: CreateSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateSessionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSession",
                service_name="agent_os.v1.SessionService",
                input=CreateSessionRequest,
                output=CreateSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_sessions(
        self,
        request: ListSessionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListSessionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSessions",
                service_name="agent_os.v1.SessionService",
                input=ListSessionsRequest,
                output=ListSessionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def attach_session(
        self,
        request: AttachSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AttachSessionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AttachSession",
                service_name="agent_os.v1.SessionService",
                input=AttachSessionRequest,
                output=AttachSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def fork_session(
        self,
        request: ForkSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ForkSessionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ForkSession",
                service_name="agent_os.v1.SessionService",
                input=ForkSessionRequest,
                output=ForkSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class SessionServiceSync(Protocol):
    def create_session(self, request: CreateSessionRequest, ctx: RequestContext[CreateSessionRequest, CreateSessionResponse]) -> CreateSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_sessions(self, request: ListSessionsRequest, ctx: RequestContext[ListSessionsRequest, ListSessionsResponse]) -> ListSessionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def attach_session(self, request: AttachSessionRequest, ctx: RequestContext[AttachSessionRequest, AttachSessionResponse]) -> AttachSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def fork_session(self, request: ForkSessionRequest, ctx: RequestContext[ForkSessionRequest, ForkSessionResponse]) -> ForkSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class SessionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: SessionServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_os.v1.SessionService/CreateSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateSession",
                        service_name="agent_os.v1.SessionService",
                        input=CreateSessionRequest,
                        output=CreateSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_session,
                ),
                "/agent_os.v1.SessionService/ListSessions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSessions",
                        service_name="agent_os.v1.SessionService",
                        input=ListSessionsRequest,
                        output=ListSessionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_sessions,
                ),
                "/agent_os.v1.SessionService/AttachSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="AttachSession",
                        service_name="agent_os.v1.SessionService",
                        input=AttachSessionRequest,
                        output=AttachSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.attach_session,
                ),
                "/agent_os.v1.SessionService/ForkSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="ForkSession",
                        service_name="agent_os.v1.SessionService",
                        input=ForkSessionRequest,
                        output=ForkSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.fork_session,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_os.v1.SessionService"


class SessionServiceClientSync(ConnectClientSync):
    def create_session(
        self,
        request: CreateSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateSessionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSession",
                service_name="agent_os.v1.SessionService",
                input=CreateSessionRequest,
                output=CreateSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_sessions(
        self,
        request: ListSessionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListSessionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSessions",
                service_name="agent_os.v1.SessionService",
                input=ListSessionsRequest,
                output=ListSessionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def attach_session(
        self,
        request: AttachSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AttachSessionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AttachSession",
                service_name="agent_os.v1.SessionService",
                input=AttachSessionRequest,
                output=AttachSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def fork_session(
        self,
        request: ForkSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ForkSessionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ForkSession",
                service_name="agent_os.v1.SessionService",
                input=ForkSessionRequest,
                output=ForkSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
