# Generated from agent_os/v1/switchers.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import common_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from .common_pb import SwitcherAxis, SwitcherScope, SwitcherState


_GetSwitcherStateRequestFields: TypeAlias = Literal["session_id"]

class GetSwitcherStateRequest(Message[_GetSwitcherStateRequestFields]):
    """
    ```proto
    message agent_os.v1.GetSwitcherStateRequest
    ```

    Attributes:
        session_id:
            Resolve in the context of this session (session > project > global). Empty
            resolves the global/project default only.

            ```proto
            string session_id = 1;
            ```
    """

    __slots__ = ("session_id",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            session_id: str = "",
        ) -> None:
            pass

        session_id: str

_GetSwitcherStateResponseFields: TypeAlias = Literal["state"]

class GetSwitcherStateResponse(Message[_GetSwitcherStateResponseFields]):
    """
    ```proto
    message agent_os.v1.GetSwitcherStateResponse
    ```

    Attributes:
        state:
            ```proto
            optional agent_os.v1.SwitcherState state = 1;
            ```
    """

    __slots__ = ("state",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            state: SwitcherState | None = None,
        ) -> None:
            pass

        state: SwitcherState | None

_SetSwitcherRequestFields: TypeAlias = Literal["axis", "value", "scope", "session_id"]

class SetSwitcherRequest(Message[_SetSwitcherRequestFields]):
    """
    ```proto
    message agent_os.v1.SetSwitcherRequest
    ```

    Attributes:
        axis:
            ```proto
            agent_os.v1.SwitcherAxis axis = 1;
            ```
        value:
            The target value (a host id, fabric name, provider id, model id or agent
            id depending on axis).

            ```proto
            string value = 2;
            ```
        scope:
            ```proto
            agent_os.v1.SwitcherScope scope = 3;
            ```
        session_id:
            Required when scope = SESSION (the session to mutate).

            ```proto
            string session_id = 4;
            ```
    """

    __slots__ = ("axis", "value", "scope", "session_id")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            axis: SwitcherAxis | None = None,
            value: str = "",
            scope: SwitcherScope | None = None,
            session_id: str = "",
        ) -> None:
            pass

        axis: SwitcherAxis
        value: str
        scope: SwitcherScope
        session_id: str

_SetSwitcherResponseFields: TypeAlias = Literal["state"]

class SetSwitcherResponse(Message[_SetSwitcherResponseFields]):
    """
    ```proto
    message agent_os.v1.SetSwitcherResponse
    ```

    Attributes:
        state:
            The new resolved state after the change.

            ```proto
            optional agent_os.v1.SwitcherState state = 1;
            ```
    """

    __slots__ = ("state",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            state: SwitcherState | None = None,
        ) -> None:
            pass

        state: SwitcherState | None

_SwitcherOptionFields: TypeAlias = Literal["value", "label", "available", "unavailable_reason"]

class SwitcherOption(Message[_SwitcherOptionFields]):
    """
    A single selectable option for an axis, with liveness for the picker UX
    (§06 SW3 / D4 §10).

    ```proto
    message agent_os.v1.SwitcherOption
    ```

    Attributes:
        value:
            ```proto
            string value = 1;
            ```
        label:
            ```proto
            string label = 2;
            ```
        available:
            Whether the option is currently usable (online host / healthy engine /
            enabled+verified cloud provider).

            ```proto
            bool available = 3;
            ```
        unavailable_reason:
            Optional reason when unavailable (e.g. host_offline, cloud_disabled).

            ```proto
            string unavailable_reason = 4;
            ```
    """

    __slots__ = ("value", "label", "available", "unavailable_reason")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            value: str = "",
            label: str = "",
            available: bool = False,
            unavailable_reason: str = "",
        ) -> None:
            pass

        value: str
        label: str
        available: bool
        unavailable_reason: str

_ListSwitcherOptionsRequestFields: TypeAlias = Literal["axis", "session_id"]

class ListSwitcherOptionsRequest(Message[_ListSwitcherOptionsRequestFields]):
    """
    ```proto
    message agent_os.v1.ListSwitcherOptionsRequest
    ```

    Attributes:
        axis:
            ```proto
            agent_os.v1.SwitcherAxis axis = 1;
            ```
        session_id:
            Context for fabric-dependent axes (provider/model options depend on the
            currently-selected fabric) and for session-scoped resolution.

            ```proto
            string session_id = 2;
            ```
    """

    __slots__ = ("axis", "session_id")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            axis: SwitcherAxis | None = None,
            session_id: str = "",
        ) -> None:
            pass

        axis: SwitcherAxis
        session_id: str

_ListSwitcherOptionsResponseFields: TypeAlias = Literal["options"]

class ListSwitcherOptionsResponse(Message[_ListSwitcherOptionsResponseFields]):
    """
    ```proto
    message agent_os.v1.ListSwitcherOptionsResponse
    ```

    Attributes:
        options:
            ```proto
            repeated agent_os.v1.SwitcherOption options = 1;
            ```
    """

    __slots__ = ("options",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            options: list[SwitcherOption] | None = None,
        ) -> None:
            pass

        options: list[SwitcherOption]


_DESC = file_desc(
    b'\n\x1bagent_os/v1/switchers.proto\x12\x0bagent_os.v1\x1a\x18agent_os/v1/common.proto"8\n\x17GetSwitcherStateRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId"L\n\x18GetSwitcherStateResponse\x120\n\x05state\x18\x01 \x01(\x0b2\x1a.agent_os.v1.SwitcherStateR\x05state"\xaa\x01\n\x12SetSwitcherRequest\x12-\n\x04axis\x18\x01 \x01(\x0e2\x19.agent_os.v1.SwitcherAxisR\x04axis\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\x120\n\x05scope\x18\x03 \x01(\x0e2\x1a.agent_os.v1.SwitcherScopeR\x05scope\x12\x1d\n\nsession_id\x18\x04 \x01(\tR\tsessionId"G\n\x13SetSwitcherResponse\x120\n\x05state\x18\x01 \x01(\x0b2\x1a.agent_os.v1.SwitcherStateR\x05state"\x89\x01\n\x0eSwitcherOption\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n\x05label\x18\x02 \x01(\tR\x05label\x12\x1c\n\tavailable\x18\x03 \x01(\x08R\tavailable\x12-\n\x12unavailable_reason\x18\x04 \x01(\tR\x11unavailableReason"j\n\x1aListSwitcherOptionsRequest\x12-\n\x04axis\x18\x01 \x01(\x0e2\x19.agent_os.v1.SwitcherAxisR\x04axis\x12\x1d\n\nsession_id\x18\x02 \x01(\tR\tsessionId"T\n\x1bListSwitcherOptionsResponse\x125\n\x07options\x18\x01 \x03(\x0b2\x1b.agent_os.v1.SwitcherOptionR\x07options2\xae\x02\n\x0fSwitcherService\x12_\n\x10GetSwitcherState\x12$.agent_os.v1.GetSwitcherStateRequest\x1a%.agent_os.v1.GetSwitcherStateResponse\x12P\n\x0bSetSwitcher\x12\x1f.agent_os.v1.SetSwitcherRequest\x1a .agent_os.v1.SetSwitcherResponse\x12h\n\x13ListSwitcherOptions\x12\'.agent_os.v1.ListSwitcherOptionsRequest\x1a(.agent_os.v1.ListSwitcherOptionsResponseb\x06proto3',
    [
        common_pb.desc(),
    ],
    {
        "GetSwitcherStateRequest": GetSwitcherStateRequest,
        "GetSwitcherStateResponse": GetSwitcherStateResponse,
        "SetSwitcherRequest": SetSwitcherRequest,
        "SetSwitcherResponse": SetSwitcherResponse,
        "SwitcherOption": SwitcherOption,
        "ListSwitcherOptionsRequest": ListSwitcherOptionsRequest,
        "ListSwitcherOptionsResponse": ListSwitcherOptionsResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `agent_os/v1/switchers.proto`."""
    return _DESC
